// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Currency identifier. Normalizes exchange-specific tickers (XBT→BTC, ZEUR→EUR).
 */
export type Asset = string;
