// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported exchange / data providers.
 */
export type Provider = "kraken" | "coinbase";
