// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Asset } from "./Asset";

/**
 * Value object: amount + currency. Arithmetic is asset-checked at runtime.
 */
export type AssetAmount = { amount: string, asset: Asset, };
