// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAmount } from "./AssetAmount";
import type { TradeSide } from "./TradeSide";

export type BepSnapshot = { date: string, side: TradeSide, held: AssetAmount, invested: AssetAmount, proceeds: AssetAmount, fees: AssetAmount, bep: string | null, };
