// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Daily OHLCV candle from Kraken. Stored in SQLite, keyed by (quote, date).
 */
export type Candle = { date: string, open: string, high: string, low: string, close: string, volume: string, count: number, };
