// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAmount } from "./AssetAmount";
import type { Candle } from "./Candle";

/**
 * Pre-computed dashboard metrics.
 */
export type DashboardStats = { 
/**
 * Latest daily close price.
 */
btc_price: AssetAmount, change_24h_pct: string, bep: AssetAmount | null, trade_count: number, held: AssetAmount, 
/**
 * held × current price.
 */
position_value: AssetAmount, 
/**
 * (current_price − BEP) × held. Zero if no open position.
 */
unrealized_pnl: AssetAmount, 
/**
 * unrealized_pnl / invested (0–1 fraction).
 */
unrealized_pnl_pct: string, 
/**
 * Full daily candle history.
 */
candles: Array<Candle>, };
