// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAmount } from "./AssetAmount";
import type { Candle } from "./Candle";

/**
 * Pre-computed dashboard metrics for the frontend stat cards.
 */
export type DashboardStats = { btc_price: AssetAmount, change_24h_pct: string, bep: AssetAmount | null, trade_count: number, held: AssetAmount, position_value: AssetAmount, unrealized_pnl: AssetAmount, unrealized_pnl_pct: string, candles: Array<Candle>, };
