// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAmount } from "./AssetAmount";

/**
 * Trade enriched with computed analytics for display.
 */
export type EnrichedTrade = { date: string, spent: AssetAmount, received: AssetAmount, fee: AssetAmount, 
/**
 * Break-even price in quote currency. None if position is fully closed.
 */
bep: AssetAmount | null, 
/**
 * Realized P&L in quote currency. None for buys.
 */
pnl: AssetAmount | null, };
