// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAmount } from "./AssetAmount";
import type { Provider } from "./Provider";
import type { TradeSide } from "./TradeSide";

/**
 * Trade enriched with computed analytics for display.
 */
export type EnrichedTrade = { date: string, provider: Provider, spent: AssetAmount, received: AssetAmount, fee: AssetAmount, 
/**
 * Trade side relative to the tracked pair. None for unrelated trades.
 */
side: TradeSide | null, 
/**
 * Break-even price in quote currency. None if position is fully closed.
 */
bep: AssetAmount | null, 
/**
 * Realized P&L in quote currency (average cost basis). None for buys.
 */
pnl: AssetAmount | null, };
