// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportRecord } from "./ImportRecord";
import type { TradesSummary } from "./TradesSummary";

/**
 * Outcome of confirming an import: the persisted record plus summary.
 */
export type ImportOutcome = { import: ImportRecord, summary: TradesSummary, 
/**
 * e.g. "5 of 12 trades were skipped (already in database)". None if no dupes.
 */
message: string | null, };
