// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";
import type { TradesSummary } from "./TradesSummary";

/**
 * Preview data for a CSV file before confirming the import.
 */
export type ImportPreview = { provider: Provider, summary: TradesSummary, file_hash: string, duplicate_trades: number, exact_file_duplicate: boolean, };
