// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";

/**
 * Persisted import record — one per CSV file successfully imported.
 */
export type ImportRecord = { id: number, provider: Provider, filename: string, file_hash: string, trade_count: number, date_from: string | null, date_to: string | null, imported_at: string, };
