// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAmount } from "./AssetAmount";

export type PositionSummary = {
  bep: string | null;
  held: AssetAmount;
  invested: AssetAmount;
  proceeds: AssetAmount;
  fees: AssetAmount;
  buys: number;
  sells: number;
};
