// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAmount } from "./AssetAmount";

/**
 * Running position state (average cost basis method).
 */
export type PositionSummary = { 
/**
 * Break-even price (average cost basis). None when position is fully closed.
 */
bep: AssetAmount | null, held: AssetAmount, 
/**
 * Total quote spent on buys (gross, before fees).
 */
invested: AssetAmount, 
/**
 * Total quote received from sells (gross, before fees).
 */
proceeds: AssetAmount, 
/**
 * Cumulative fees normalized to quote currency.
 */
fees: AssetAmount, buys: number, sells: number, };
