// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Direction relative to the tracked pair, not the raw ledger row.
 */
export type TradeSide = "Buy" | "Sell" | "Reward";
