// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetAmount } from "./AssetAmount";

/**
 * Aggregate stats for a set of trades.
 */
export type TradesSummary = { total_trades: number, buys: number, sells: number, 
/**
 * Trades that don't match the tracked pair (e.g. ETH/USD in a BTC/EUR context).
 */
unknown: number, date_range: [string, string] | null, spent: AssetAmount, received: AssetAmount, 
/**
 * Fees normalized to quote currency (BTC fees converted via trade price).
 */
fees: AssetAmount, };
